#pragma once

// Umbrella header — pulls in the full SymPP public surface.
// For finer control (e.g. include only what you need), use the per-module headers.

#include <sympp/core/add.hpp>
#include <sympp/core/assumption_key.hpp>
#include <sympp/core/assumption_mask.hpp>
#include <sympp/core/basic.hpp>
#include <sympp/core/boolean.hpp>
#include <sympp/core/expand.hpp>
#include <sympp/core/expr_cache.hpp>
#include <sympp/core/expr_collections.hpp>
#include <sympp/core/float.hpp>
#include <sympp/core/function.hpp>
#include <sympp/core/function_id.hpp>
#include <sympp/core/imaginary_unit.hpp>
#include <sympp/core/integer.hpp>
#include <sympp/core/mul.hpp>
#include <sympp/core/number.hpp>
#include <sympp/core/number_arith.hpp>
#include <sympp/core/number_symbol.hpp>
#include <sympp/core/operators.hpp>
#include <sympp/core/piecewise.hpp>
#include <sympp/core/pow.hpp>
#include <sympp/core/queries.hpp>
#include <sympp/core/refine.hpp>
#include <sympp/core/rational.hpp>
#include <sympp/core/singletons.hpp>
#include <sympp/core/symbol.hpp>
#include <sympp/core/traversal.hpp>
#include <sympp/core/type_id.hpp>
#include <sympp/core/undefined_function.hpp>
#include <sympp/calculus/diff.hpp>
#include <sympp/calculus/euler_lagrange.hpp>
#include <sympp/calculus/extrema.hpp>
#include <sympp/calculus/limit.hpp>
#include <sympp/calculus/order.hpp>
#include <sympp/calculus/pade.hpp>
#include <sympp/calculus/series.hpp>
#include <sympp/calculus/summation.hpp>
#include <sympp/functions/combinatorial.hpp>
#include <sympp/functions/exponential.hpp>
#include <sympp/functions/hyperbolic.hpp>
#include <sympp/functions/integers.hpp>
#include <sympp/functions/miscellaneous.hpp>
#include <sympp/functions/special.hpp>
#include <sympp/functions/trigonometric.hpp>
#include <sympp/integrals/integrate.hpp>
#include <sympp/integrals/transforms.hpp>
#include <sympp/matrices/matrix.hpp>
#include <sympp/polys/poly.hpp>
#include <sympp/polys/rootof.hpp>
#include <sympp/simplify/simplify.hpp>
#include <sympp/solvers/solve.hpp>
#include <sympp/fwd.hpp>
#include <sympp/version.hpp>
